// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/addcoupen": {
            "post": {
                "description": "Admin can add coupen here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "coupen management"
                ],
                "summary": "ADD COUPEN",
                "operationId": "add-coupen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "minimumamount",
                        "name": "minimumamount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "amount",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/addproduct": {
            "post": {
                "description": "Add new products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "product management"
                ],
                "summary": "Add Products",
                "operationId": "add-product",
                "parameters": [
                    {
                        "description": "Product details",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ProductsResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/block": {
            "post": {
                "description": "admin can block user here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "user management"
                ],
                "summary": "BLOCK USER",
                "operationId": "block user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/deleteproducts": {
            "delete": {
                "description": "admin can delete product here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "product management"
                ],
                "summary": "DELETE PRODUCT",
                "operationId": "delete-product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/editproduct": {
            "patch": {
                "description": "admin can edit product here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "product management"
                ],
                "summary": "EDIT PRODUCT",
                "operationId": "edit-product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "product_id",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "product name",
                        "name": "product_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "product colour",
                        "name": "product_colour",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "product size",
                        "name": "product_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "product price",
                        "name": "product_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "stock",
                        "name": "stock",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/listcoupen": {
            "get": {
                "description": "Admin can list coupen here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "coupen management"
                ],
                "summary": "LIST COUPEN",
                "operationId": "list-coupen",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/returnstatus": {
            "post": {
                "description": "admin can see delivery status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "delivery status"
                ],
                "summary": "ReturnStatus",
                "operationId": "return status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "paymentid",
                        "name": "paymentid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/salesreport": {
            "get": {
                "description": "Admin can download sales report from here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "sales report"
                ],
                "summary": "sales report",
                "operationId": "sales report",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/speacificuser": {
            "get": {
                "description": "admin can view specific user here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "user management"
                ],
                "summary": "VIEW SPECIFIC USER",
                "operationId": "view-specific user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User_Name",
                        "name": "User_Name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "Email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Phone_Number",
                        "name": "Phone_Number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/superadminlogin": {
            "post": {
                "description": "Admin can sign up with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "home"
                ],
                "summary": "Admin Login",
                "operationId": "Admin-login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AdminLoginResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/unblock": {
            "post": {
                "description": "admin can unblock user here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "user management"
                ],
                "summary": "UnBLOCK USER",
                "operationId": "unblock user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/view": {
            "get": {
                "description": "admin can view user here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "user management"
                ],
                "summary": "VIEW USER",
                "operationId": "view-user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/viewblockedusers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a list of blocked users with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "user management"
                ],
                "summary": "Get blocked users",
                "operationId": "blockedusers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/viewproducts": {
            "get": {
                "description": "admin can view product here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "product management"
                ],
                "summary": "VIEW PRODUCT",
                "operationId": "view-product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/admin/viewunblockedusers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a list of active users with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "user management"
                ],
                "summary": "Get un blocked users",
                "operationId": "unblockedusers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/aboutme": {
            "get": {
                "description": "user can view profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "profile management"
                ],
                "summary": "VIEW  PROFILE",
                "operationId": "view-profile",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/addaddress": {
            "post": {
                "description": "User can add their address here...",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "address management"
                ],
                "summary": "Add Address",
                "operationId": "add-address",
                "parameters": [
                    {
                        "description": "Address data",
                        "name": "AddAddressResponse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddAddressResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/addcart": {
            "post": {
                "description": "User can add items to their cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "cart management"
                ],
                "summary": "Add Cart",
                "operationId": "add-cart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product_ID",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Product_Quantity",
                        "name": "product_quantity",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/addorder": {
            "post": {
                "description": "user can add order here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "order management"
                ],
                "summary": "ADD ORDER",
                "operationId": "add-order",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/addwishlist": {
            "post": {
                "description": "Adds a product to the user's wishlist based on the provided ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "wishlist"
                ],
                "summary": "Add a product to the wishlist",
                "operationId": "addwishlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the product to add to the wishlist",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/applycoupens": {
            "post": {
                "description": "user can apply coupen here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "coupen"
                ],
                "summary": "APPLY COUPEN",
                "operationId": "applycoupen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "coupenname",
                        "name": "coupenname",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/cancelorder": {
            "delete": {
                "description": "user can cancel order here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "order management"
                ],
                "summary": "CANCEL ORDER",
                "operationId": "cancel-order",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/changepassword": {
            "post": {
                "description": "User can change password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "Change password"
                ],
                "summary": "Change password",
                "operationId": "change-password",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/deleteaddress": {
            "delete": {
                "description": "Delete address of a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "address management"
                ],
                "summary": "Delete address",
                "operationId": "delete-address",
                "parameters": [
                    {
                        "description": "Idelete addressD ",
                        "name": "AddResponse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/deleteitem": {
            "delete": {
                "description": "User delete cart items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "cart management"
                ],
                "summary": "delete-cart items",
                "operationId": "delete-cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "productId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "quantity",
                        "name": "quantity",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/deleteprofile": {
            "delete": {
                "description": "user can delete profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "profile management"
                ],
                "summary": "DELETE  PROFILE",
                "operationId": "delete-profile",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/editaddress": {
            "patch": {
                "description": "User can change their address here ...",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "address management"
                ],
                "summary": "Edit Address",
                "operationId": "edit-address",
                "parameters": [
                    {
                        "description": "information",
                        "name": "EditAddressResponse",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.EditAddressResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/editmyprofile": {
            "patch": {
                "description": "Edit user profile with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "profile management"
                ],
                "summary": "Edit user profile",
                "operationId": "edit-profile",
                "parameters": [
                    {
                        "description": "informations",
                        "name": "EditprofileResponse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EditprofileResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/forgot": {
            "post": {
                "description": "User can change password here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "Forget password"
                ],
                "summary": "forgot password",
                "operationId": "forgot_password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "Email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "phone_number",
                        "name": "Phonenumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "newpassword",
                        "name": "newpassword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "confirmpassword",
                        "name": "confirmpassword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/listcoupens": {
            "get": {
                "description": "user can list coupen here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "coupen"
                ],
                "summary": "LIST COUPEN",
                "operationId": "listcoupen",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/listwishlist": {
            "get": {
                "description": "Retrieves the wishlist for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "wishlist"
                ],
                "summary": "Get the user's wishlist",
                "operationId": "list_wishlist",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/loginuser": {
            "post": {
                "description": "User can login here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "Home"
                ],
                "summary": "User LOGIN",
                "operationId": "user-LOGIN",
                "parameters": [
                    {
                        "description": "user credentials for creating new account",
                        "name": "newUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserLoginResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/mywallet": {
            "get": {
                "description": "user can view wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "My Wallet"
                ],
                "summary": "My Wallet",
                "operationId": "My_Wallet",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/payment-success": {
            "get": {
                "description": "razor pay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "payment manangement"
                ],
                "summary": "RAZOR PAY",
                "operationId": "razor-pay-success",
                "parameters": [
                    {
                        "type": "string",
                        "description": "paymentid",
                        "name": "paymentid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "orderid",
                        "name": "orderid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/razorpay": {
            "get": {
                "description": "razor pay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "payment manangement"
                ],
                "summary": "RAZOR PAY",
                "operationId": "razor-pay",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/removewishlist": {
            "delete": {
                "description": "user can delete items of their wishlist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "wishlist"
                ],
                "summary": "REMOVE WISHLIST",
                "operationId": "remove_wishlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/returnproduct": {
            "post": {
                "description": "user can return product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "return product"
                ],
                "summary": "RETURN PRODUCT",
                "operationId": "return product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "orderid",
                        "name": "orderid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "productid",
                        "name": "productid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/showorder": {
            "get": {
                "description": "user can view order here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "order management"
                ],
                "summary": "SHOW ORDER",
                "operationId": "show-order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "User can sign up with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "Home"
                ],
                "summary": "User Signup",
                "operationId": "user-signup",
                "parameters": [
                    {
                        "description": "user credentials for creating new account",
                        "name": "newUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserSignupResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/verifyotp": {
            "post": {
                "description": "User can verify otp for password change",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "Change password"
                ],
                "summary": "VERIFY OTP",
                "operationId": "verify--otp",
                "parameters": [
                    {
                        "description": "OTP Verification Request",
                        "name": "VerifyOtpResponse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.VerifyOtpResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/viewaddress": {
            "get": {
                "description": "User can view their address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "address management"
                ],
                "summary": "viewaddress",
                "operationId": "view-address",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/viewcart": {
            "get": {
                "description": "User can view their cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "cart management"
                ],
                "summary": "View Cart",
                "operationId": "view-cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user/viewproduct": {
            "get": {
                "description": "user can view product here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "products"
                ],
                "summary": "viewproduct",
                "operationId": "vieproduct",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "perpage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AddAddressResponse": {
            "type": "object",
            "properties": {
                "district": {
                    "type": "string"
                },
                "house_name": {
                    "type": "string"
                },
                "pin_Number": {
                    "type": "integer"
                },
                "place": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "handlers.AddResponse": {
            "type": "object",
            "required": [
                "address_id"
            ],
            "properties": {
                "address_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.AdminLoginResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.EditAddressResponse": {
            "type": "object",
            "properties": {
                "district": {
                    "type": "string"
                },
                "house_name": {
                    "type": "string"
                },
                "pin_Number": {
                    "type": "integer"
                },
                "place": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "handlers.EditprofileResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "phone_Number": {
                    "type": "string"
                },
                "user_Name": {
                    "type": "string"
                }
            }
        },
        "handlers.ProductsResponse": {
            "type": "object",
            "required": [
                "product_brand",
                "product_colour",
                "product_name",
                "product_size"
            ],
            "properties": {
                "product_Price": {
                    "type": "integer"
                },
                "product_brand": {
                    "type": "string"
                },
                "product_colour": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "product_size": {
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                }
            }
        },
        "handlers.UserLoginResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.UserSignupResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_Number": {
                    "type": "string"
                },
                "user_Name": {
                    "type": "string"
                }
            }
        },
        "handlers.VerifyOtpResponse": {
            "type": "object",
            "properties": {
                "confirm_Password": {
                    "type": "string"
                },
                "new_Password": {
                    "type": "string"
                },
                "otp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ORCHID_FOOTWARES",
	Description:      "<add description here>",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
