basePath: /
definitions:
  handlers.AdminLoginResponse:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.BlockedUsersResponse:
    properties:
      page:
        type: integer
      perpage:
        type: integer
    type: object
  handlers.ProductsResponse:
    properties:
      product_Price:
        type: integer
      product_brand:
        type: string
      product_colour:
        type: string
      product_name:
        type: string
      product_size:
        type: integer
      stock:
        type: integer
    required:
    - product_brand
    - product_colour
    - product_name
    - product_size
    type: object
  handlers.UserLoginResponse:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.UserSignupResponse:
    properties:
      email:
        type: string
      password:
        type: string
      phone_Number:
        type: string
      user_Name:
        type: string
    type: object
host: localhost:9080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: <add description here>
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: ORCHID_FOOTWARES
  version: "1.0"
paths:
  /admin/addproduct:
    post:
      consumes:
      - application/json
      description: Add new products
      operationId: add-product
      parameters:
      - description: Product details
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/handlers.ProductsResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Add Products
      tags:
      - Admin
      - product management
  /admin/block:
    post:
      consumes:
      - application/json
      description: admin can block user here
      operationId: block user
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: BLOCK USER
      tags:
      - Admin
      - user management
  /admin/deleteproducts:
    delete:
      consumes:
      - application/json
      description: admin can delete product here
      operationId: delete-product
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: DELETE PRODUCT
      tags:
      - Admin
      - product management
  /admin/editproduct:
    patch:
      consumes:
      - application/json
      description: admin can edit product here
      operationId: edit-product
      parameters:
      - description: product_id
        in: query
        name: product_id
        required: true
        type: integer
      - description: product name
        in: query
        name: product_name
        type: string
      - description: product colour
        in: query
        name: product_colour
        type: string
      - description: product size
        in: query
        name: product_size
        type: integer
      - description: product price
        in: query
        name: product_price
        type: integer
      - description: stock
        in: query
        name: stock
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: EDIT PRODUCT
      tags:
      - Admin
      - product management
  /admin/speacificuser:
    get:
      consumes:
      - application/json
      description: admin can view specific user here
      operationId: view-specific user
      parameters:
      - description: Id
        in: query
        name: id
        type: integer
      - description: User_Name
        in: query
        name: User_Name
        type: string
      - description: Email
        in: query
        name: Email
        type: string
      - description: Phone_Number
        in: query
        name: Phone_Number
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: VIEW SPECIFIC USER
      tags:
      - Admin
      - user management
  /admin/superadminlogin:
    post:
      consumes:
      - application/json
      description: Admin can sign up with email and password
      operationId: Admin-login
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/handlers.AdminLoginResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Admin Login
      tags:
      - Admin
      - home
  /admin/unblock:
    post:
      consumes:
      - application/json
      description: admin can unblock user here
      operationId: unblock user
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: UnBLOCK USER
      tags:
      - Admin
      - user management
  /admin/view:
    get:
      consumes:
      - application/json
      description: admin can view user here
      operationId: view-user
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: perpage
        in: query
        name: perpage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: VIEW USER
      tags:
      - Admin
      - user management
  /admin/viewblockedusers:
    get:
      consumes:
      - application/json
      description: Retrieve a list of blocked users with pagination
      operationId: blockedusers
      parameters:
      - description: Pagination details
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/handlers.BlockedUsersResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Get blocked users
      tags:
      - Admin
      - user management
  /admin/viewproducts:
    get:
      consumes:
      - application/json
      description: admin can view product here
      operationId: view-product
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: perpage
        in: query
        name: perpage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: VIEW PRODUCT
      tags:
      - Admin
      - product management
  /user/aboutme:
    get:
      consumes:
      - application/json
      description: user can view profile
      operationId: view-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: VIEW  PROFILE
      tags:
      - User
      - profile management
  /user/changepassword:
    post:
      consumes:
      - application/json
      description: User can change password
      operationId: change-password
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Change password
      tags:
      - User
      - Change password
  /user/deleteitem:
    delete:
      consumes:
      - application/json
      description: User delete cart items
      operationId: delete-cart
      parameters:
      - description: id
        in: query
        name: productId
        required: true
        type: string
      - description: quantity
        in: query
        name: quantity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: delete-cart items
      tags:
      - User
      - cart management
  /user/loginuser:
    post:
      consumes:
      - application/json
      description: User can login here
      operationId: user-LOGIN
      parameters:
      - description: user credentials for creating new account
        in: body
        name: newUser
        required: true
        schema:
          $ref: '#/definitions/handlers.UserLoginResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: User LOGIN
      tags:
      - User
      - Home
  /user/signup:
    post:
      consumes:
      - application/json
      description: User can sign up with email and password
      operationId: user-signup
      parameters:
      - description: user credentials for creating new account
        in: body
        name: newUser
        required: true
        schema:
          $ref: '#/definitions/handlers.UserSignupResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: User Signup
      tags:
      - User
      - Home
  /user/viewcart:
    get:
      consumes:
      - application/json
      description: User can view their cart
      operationId: view-cart
      parameters:
      - description: 'Page '
        in: query
        name: page
        required: true
        type: string
      - description: perpage
        in: query
        name: perpage
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: View Cart
      tags:
      - User
      - cart management
  /user/viewproduct:
    get:
      consumes:
      - application/json
      description: user can view product here
      operationId: vieproduct
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: perpage
        in: query
        name: perpage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: viewproduct
      tags:
      - User
      - products
swagger: "2.0"
